AllCops:
  TargetRubyVersion: 2.5.1
  TargetRailsVersion: 5.2.1
  Exclude:
    - "db/**/*"
    - "config/**/*"
    - "script/**/*"
    - "bin/{bundle,rails,rake,setup,spring,update,yarn}"
    - "config.ru"

Style/StringLiterals:
  EnforcedStyle: double_quotes

Metrics/ClassLength:
  Exclude:
    - "test/**/*_test.rb"
