AllCops:
  TargetRubyVersion: 2.5.1
  TargetRailsVersion: 5.2.1
  Exclude:
    - 'db/**/*'
    - 'config/**/*'
    - 'script/**/*'
    - 'bin/{rails,rake}'

Style/StringLiterals:
  EnforcedStyle: double_quotes
